apiVersion: v1
kind: ConfigMap
metadata:
  name: rssfeed-config
data:
  application.properties:
    spring.application.name=rssFeed

    server.port=8887
    server.servlet.context-path=/v1/api/rssFeed

    spring.data.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017
    spring.data.mongodb.database=SOAP
    nasa-client.url=https://www.nasa.gov/news-release/feed/
    nasa-client.cron=*/5 * * * * *
