apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rssfeed-ingress
spec:
  rules:
    - host: rssfeed-dev
      http:
        paths:
          - path: /rssfeed
            pathType: Prefix
            backend:
              service:
                name: rssfeed-dev
                port:
                  number: 3000
