apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rssfeed
  namespace: rssfeed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rssfeed
  template:
    metadata:
      labels:
        app: rssfeed
    spec:
      containers:
        - name: rssfeed
          image: "rssfeed:latest"
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env: []
          resources:
            limits:
              cpu: 500m
              memory: 2500Mi
            requests:
              cpu: 200m
              memory: 1500Mi
          envFrom:
            - secretRef:
                name: rssfeed-secret
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause:
            duration: 10s
        - setWeight: 100
