apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rssfeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rssfeed
  template:
    metadata:
      labels:
        app: rssfeed
    spec:
      containers:
        - name: rssfeed
          image: "iosilva/rssfeed:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >
                -Duser.timezone=America/Sao_Paulo
                -XX:MinRAMPercentage=10
                -XX:MaxRAMPercentage=75
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://admin:admin123456@mongo-mongodb:27017
          resources:
            limits:
              cpu: 500m
              memory: 2500Mi
            requests:
              cpu: 200m
              memory: 1500Mi
          envFrom:
            - configMapRef:
                name: rssfeed-config
            - secretRef:
                name: rssfeed-secret
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause:
            duration: 10s
        - setWeight: 100
